version: '3'
services:
  sourcebot:
    build:
      dockerfile: Dockerfile.sourcebot
    environment:
      - ZOEKT_WEBSERVER_URL=http://zoekt-webserver:6070
    ports:
      - 3000:3000

  zoekt-indexserver:
    build:
      dockerfile: Dockerfile.zoekt-indexserver
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - CONFIG_PATH=/app/configs/config.json
      - ZOEKT_DATA_CACHE_DIR=/zoekt-data/
    volumes:
      - ./configs/config.json:/app/configs/config.json:r
      - zoekt_data_cache:/zoekt-data/

  zoekt-webserver:
    build:
      dockerfile: Dockerfile.zoekt-webserver
    environment:
      - ZOEKT_DATA_CACHE_DIR=/zoekt-data/
    volumes:
      - zoekt_data_cache:/zoekt-data/
  
volumes:
  zoekt_data_cache: